### ISSUE TITLE
Errors During installation on Mac M1

### ISSUE THREAD

**Issue by kamal2222ahmed** [websu-io/websu#27]
Here is the Complete run as per instructions:
```
 docker-compose up -d
[+] Running 20/20
 ✔ websu-api 4 layers [⣿⣿⣿⣿]      0B/0B      Pulled                                                                                                                                                                         
[+] Running 5/6
 ✔ Network websu_default                                                                                                                                            Created                                                 0.0s
 ✔ Container websu-mongo-1                                                                                                                                          Started                                                 0.6s
 ✔ Container websu-lighthouse-server-1                                                                                                                              Started                                                 0.6s
```
errors:
```
 ! lighthouse-server The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                                                         0.0s
 ⠿ Container websu-websu-api-1                                                                                                                                      Starting                                                0.7s
 ! websu-api The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                                                                 0.0s
Error response from daemon: error while creating mount source path '/Users/syedahmed/QA/TOOLS/WEBSU/websu/firebase-sa.json': chown /Users/syedahmed/QA/TOOLS/WEBSU/websu/firebase-sa.json: permission denied
```
➜  websu git:(master) docker ps
```
CONTAINER ID   IMAGE                                      COMMAND                  CREATED          STATUS          PORTS                        NAMES
4e40a2ff1338   mongo:4                                    "docker-entrypoint.s…"   43 minutes ago   Up 43 minutes   127.0.0.1:27017->27017/tcp   websu-mongo-1
f6ade17ce313   samos123/lighthouse-server-docker:latest   "/websu/lighthouse-s…"   43 minutes ago   Up 43 minutes   127.0.0.1:50051->50051/tcp   websu-lighthouse-server-1
```
➜  websu git:(master) curl -d '{"url": "https://www.google.com"}' localhost:8000/reports
```
curl: (7) Failed to connect to localhost port 8000 after 0 ms: Couldn't connect to server
```

**Comment by kamal2222ahmed** [comment]
I added the platform:
```
version: '3.0'
services:
  websu-api:
    image: samos123/websu-api:latest
    platform: linux/amd64
    ports:
    - "8000:8000"
    environment:
    - "LIGHTHOUSE_SERVER=lighthouse-server:50051"
    - "MONGO_URI=mongodb://mongo:27017"
    - "SERVE_FRONTEND=false"
    - "AUTH=firebase"
    - "GOOGLE_APPLICATION_CREDENTIALS=/firebase-sa.json"
    volumes:
      - ./firebase-sa.json:/firebase-sa.json
    links:
    - mongo
    - lighthouse-server
  lighthouse-server:
    image: samos123/lighthouse-server-docker:latest
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - "127.0.0.1:50051:50051"
  mongo:
    image: mongo:4
    ports:
    - "127.0.0.1:27017:27017"
```
still could not bring up the web service on 8000
```
NAME                        IMAGE                                      COMMAND                  SERVICE             CREATED             STATUS              PORTS
websu-lighthouse-server-1   samos123/lighthouse-server-docker:latest   "/websu/lighthouse-s…"   lighthouse-server   23 seconds ago      Up 21 seconds       127.0.0.1:50051->50051/tcp
websu-mongo-1               mongo:4                                    "docker-entrypoint.s…"   mongo               23 seconds ago      Up 21 seconds       127.0.0.1:27017->27017/tcp
websu-websu-api-1           samos123/websu-api:latest                  "/websu/websu-api"       websu-api           23 seconds ago      Up 20 seconds       0.0.0.0:8000->8000/tcp, :::8000->8000/tcp
➜  websu git:(master) ✗ curl -d '{"url": "https://www.google.com"}' localhost:8000/
curl: (7) Failed to connect to localhost port 8000 after 0 ms: Couldn't connect to server
```
